spring:
  profiles:
    group:
      dev: development
      prod: production
    active: dev

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:gcp-credentials.json
        project-id: feisty-ward-411905
        bucket: gces_bucket

default:
  string: default property

jwt:
  secret: ${application.jwt.secret}
  secret_refresh: ${application.jwt.secret_refresh}
  access_token_expire: ${application.jwt.access_token_expire}
  refresh_token_expire: ${application.jwt.refresh_token_expire}
