spring:
  profiles:
    group:
      dev: development
      prod: production
    active: dev

default:
  string: default property

jwt:
  secret: ${application.jwt.secret}
  secret_refresh: ${application.jwt.secret_refresh}
